# Generated by Django 2.2.2 on 2019-06-22 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190622_0756'),
        ('users', '0003_remove_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='blog.Post'),
        ),
    ]
