# Generated by Django 2.2.2 on 2019-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190622_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='postss', to='blog.Tag'),
        ),
    ]
