# Generated by Django 2.2.2 on 2019-07-05 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_auto_20190705_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_saved',
            field=models.ManyToManyField(blank=True, default='', related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
