# Generated by Django 2.2.2 on 2019-07-05 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
