# Generated by Django 2.2.2 on 2019-07-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190705_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_saved',
            new_name='saves',
        ),
    ]
