# Generated by Django 2.2.2 on 2019-07-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190706_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown_field',
            field=models.TextField(default='some text'),
        ),
    ]
