# Generated by Django 2.2.2 on 2019-07-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_markdown_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown_field',
        ),
    ]
